apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: ClusterIP  # Restricts access to within the cluster
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80            # Internal service port
      targetPort: 80      # Container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx  # Change this to "nginx" for NGINX Ingress Controller
  tls:
    - hosts:
        - error-page.wingserp.net
      secretName: wingerp.net-tls  # Ensure this secret exists in the "default" namespace
  rules:
    - host: error-page.wingserp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80  # Ensure your Nginx pod is listening on port 80


